### ISSUE TITLE
Update property

### ISSUE THREAD

**Issue by bbriatte** [Digipolitan/polymorph-cli#1]
edit the property update to works like new property

**Comment by L00rdD** [comment]
issue while adding a transformer to a property during update
poly class property update propertyName -c className -pnn --transformer date 
returns : **[!] Unexpected error occured: propertyNotFound("date")**
should return :  
**Transformer 'date' options setup**
**format (yyyy-MM-dd'T'HH:mm:ssZZZ) :**

**Comment by bbriatte** [comment]
fix https://github.com/Digipolitan/polymorph-cli/releases/tag/v1.0.3
