### ISSUE TITLE
Update property class type

### ISSUE THREAD

**Issue by L00rdD** [Digipolitan/polymorph-cli#3]
Failed on updating property class type
(Tryied to update property type from **Date** to **String**)
command: **"polymorph class property update propertyName -c ClassName -t string** 
result: **[!] Unexpected error occured: objectNotFound("String")**
Idea: could be when trying to find string only looking on project and not on native class ?

**Comment by bbriatte** [comment]
fix https://github.com/Digipolitan/polymorph-cli/releases/tag/v1.0.3
